/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2021.2.6                                                    */
/* Component Version:  V2021.2.5                                                    */
/* CAS Version:        V.04.00M0P04182022                                           */
/* SAS Version:        V.04.00M0P041822                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       908833a3-7674-4070-8a3e-417a17ab994b                         */
/* Node GUID:          4336bbd8-af48-4b00-9d97-288923abeadc                         */
/* Node Id:            3Z92HC9YI6ZHE5UN574K8Z7X8                                    */
/* Algorithm:          Gradient Boosting                                            */
/* Generated by:       Paata.Ugrekhelidze@sas.com                                   */
/* Date:               31MAY2022:20:00:15                                           */
/*----------------------------------------------------------------------------------*/
data sasep.out;
   dcl package score _1J68GWITTUN3IYFNRA77PA4VW();
   dcl double "Age";
   dcl double "DBP";
   dcl double "HospAdmTime";
   dcl double "Hour";
   dcl double "HR";
   dcl double "ICULOS";
   dcl double "MAP";
   dcl double "O2Sat";
   dcl double "Resp";
   dcl double "SBP";
   dcl double "Var1";
   dcl double "Gender";
   dcl varchar(3) "Unit1";
   dcl varchar(3) "Unit2";
   dcl package score _3Z92HC9YI6ZHE5UN574K8Z7X8();
   dcl double "cpy_int_med_imp_Age" having label n'Age: Low missing rate - median imputation';
   dcl double EM_EVENTPROBABILITY;
   dcl double "cpy_int_med_imp_HospAdmTime" having label n'HospAdmTime: Low missing rate - median imputation';
   dcl nchar(12) EM_CLASSIFICATION;
   dcl double "cpy_int_med_imp_Hour" having label n'Hour: Low missing rate - median imputation';
   dcl double EM_PROBABILITY;
   dcl double "cpy_int_med_imp_ICULOS" having label n'ICULOS: Low missing rate - median imputation';
   dcl double "cpy_int_med_imp_O2Sat" having label n'O2Sat: Low missing rate - median imputation';
   dcl double "cpy_int_med_imp_Var1" having label n'Var1: Low missing rate - median imputation';
   dcl double "nhoks_nloks_pow_n1_DBP" having label n'DBP: Not high (outlier, kurtosis, skewness) - power(-1) + impute(median)';
   dcl double "nhoks_nloks_pow_n1_HR" having label n'HR: Not high (outlier, kurtosis, skewness) - power(-1) + impute(median)';
   dcl double "nhoks_nloks_pow_n1_MAP" having label n'MAP: Not high (outlier, kurtosis, skewness) - power(-1) + impute(median)';
   dcl double "nhoks_nloks_pow_n1_Resp" having label n'Resp: Not high (outlier, kurtosis, skewness) - power(-1) + impute(median)';
   dcl double "nhoks_nloks_pow_n1_SBP" having label n'SBP: Not high (outlier, kurtosis, skewness) - power(-1) + impute(median)';
   dcl double "nhoks_nloks_pow_p2_DBP" having label n'DBP: Not high (outlier, kurtosis, skewness) - power(2) + impute(median)';
   dcl double "all_l_oks_dtree_5_Age" having label n'Age: Low (outlier, kurtosis, skewness) - five bin decision tree binning';
   dcl double "cpy_nom_miss_lev_lab_Unit1" having label n'Unit1: Low missing rate - missing level';
   dcl double "cpy_nom_miss_lev_lab_Unit2" having label n'Unit2: Low missing rate - missing level';
   dcl double "cpy_nom_mode_imp_lab_Gender" having label n'Gender: Low missing rate - mode imputation + label transformation';
   dcl double "miss_ind_DBP" having label n'DBP: Significant missing - missing indicator';
   dcl double "miss_ind_HR" having label n'HR: Significant missing - missing indicator';
   dcl double "miss_ind_MAP" having label n'MAP: Significant missing - missing indicator';
   dcl double "miss_ind_O2Sat" having label n'O2Sat: Significant missing - missing indicator';
   dcl double "miss_ind_Resp" having label n'Resp: Significant missing - missing indicator';
   dcl double "miss_ind_SBP" having label n'SBP: Significant missing - missing indicator';
   dcl double "miss_ind_Unit1" having label n'Unit1: Significant missing - missing indicator';
   dcl double "miss_ind_Unit2" having label n'Unit2: Significant missing - missing indicator';
   dcl double "nhoks_nloks_dtree_5_HR" having label n'HR: Not high (outlier, kurtosis, skewness) - five bin decision tree binning';
   dcl double "nhoks_nloks_dtree_5_MAP" having label n'MAP: Not high (outlier, kurtosis, skewness) - five bin decision tree binning';
   dcl double "nhoks_nloks_dtree_5_Resp" having label n'Resp: Not high (outlier, kurtosis, skewness) - five bin decision tree binning';
   dcl double "nhoks_nloks_dtree_5_SBP" having label n'SBP: Not high (outlier, kurtosis, skewness) - five bin decision tree binning';
   dcl double "P_SepsisLabel1" having label n'Predicted: SepsisLabel=1';
   dcl double "P_SepsisLabel0" having label n'Predicted: SepsisLabel=0';
   dcl nchar(32) "I_SepsisLabel" having label n'Into: SepsisLabel';
   dcl nchar(4) "_WARN_" having label n'Warnings';
   dcl nchar(6) "Alkalinephos" having label n'Alkalinephos';
   dcl nchar(6) "AST" having label n'AST';
   dcl nchar(4) "Bilirubin_direct" having label n'Bilirubin_direct';
   dcl nchar(4) "Bilirubin_total" having label n'Bilirubin_total';
   dcl nchar(6) "Fibrinogen" having label n'Fibrinogen';
   dcl double "Patient_ID" having label n'Patient_ID';
   dcl nchar(5) "SaO2" having label n'SaO2';
   dcl nchar(6) "TroponinI" having label n'TroponinI';
   varlist allvars [_all_];
 
    
   method init();
      _1J68GWITTUN3IYFNRA77PA4VW.setvars(allvars);
      _1J68GWITTUN3IYFNRA77PA4VW.setkey(n'264A00A4821C844CE5EBF46225C604C0199BE914');
      _3Z92HC9YI6ZHE5UN574K8Z7X8.setvars(allvars);
      _3Z92HC9YI6ZHE5UN574K8Z7X8.setkey(n'665A452B6B473B572B96EBB324165F9FE08E0EB6');
   end;
    
   method post_3Z92HC9YI6ZHE5UN574K8Z7X8();
      dcl double _P_;
      dcl double _SUM;
       
      if "P_SEPSISLABEL0" = . then "P_SEPSISLABEL0" = 0.5;
      if "P_SEPSISLABEL1" = . then "P_SEPSISLABEL1" = 0.5;
      if MISSING("I_SEPSISLABEL") then do ;
      _P_ = 0.0;
      if "P_SEPSISLABEL1" > _P_ then do ;
      _P_ = "P_SEPSISLABEL1";
      "I_SEPSISLABEL" = '           1';
      end;
      if "P_SEPSISLABEL0" > _P_ then do ;
      _P_ = "P_SEPSISLABEL0";
      "I_SEPSISLABEL" = '           0';
      end;
      end;
      "P_SEPSISLABEL0" = "P_SEPSISLABEL0" * 0.9820153201 / 0.5;
      "P_SEPSISLABEL1" = "P_SEPSISLABEL1" * 0.0179846799 / 0.5;
      _SUM = "P_SEPSISLABEL0" + "P_SEPSISLABEL1";
      "P_SEPSISLABEL0" = "P_SEPSISLABEL0" / _SUM;
      "P_SEPSISLABEL1" = "P_SEPSISLABEL1" / _SUM;
      _P_ = 0.0;
      if "P_SEPSISLABEL1" > _P_ then do ;
      _P_ = "P_SEPSISLABEL1";
      "I_SEPSISLABEL" = '           1';
      end;
      if "P_SEPSISLABEL0" > _P_ then do ;
      _P_ = "P_SEPSISLABEL0";
      "I_SEPSISLABEL" = '           0';
      end;
      EM_EVENTPROBABILITY = "P_SEPSISLABEL1";
      EM_CLASSIFICATION = "I_SEPSISLABEL";
      EM_PROBABILITY = MAX("P_SEPSISLABEL1", "P_SEPSISLABEL0");
    
   end;
    
 
   method run();
      set SASEP.IN;
      _1J68GWITTUN3IYFNRA77PA4VW.scoreRecord();
      _3Z92HC9YI6ZHE5UN574K8Z7X8.scoreRecord();
      post_3Z92HC9YI6ZHE5UN574K8Z7X8();
   end;
 
   method term();
   end;
 
enddata;
