data sasep.out;
  dcl package score sc();
  dcl varchar(32767) "Review_Text";
  dcl varchar(32767) "_concepts_" having label n'Concepts';
  dcl varchar(32767) "_facts_" having label n'Facts';
  varlist allvars[_all_];
  method init();
    sc.setvars(allvars);
    sc.setKey(n'572502A5DAF0E5EBA20DA2A5D209AEE7D923FF6D');
  end;
  method preScoreRecord();
  end;
  method postScoreRecord();
  end;
  method term();
  end;
  method run();
    set sasep.in;
    preScoreRecord();
    sc.scoreRecord();
    postScoreRecord();
  end;
enddata;
