data sasep.out;
  dcl package score sc();
  dcl varchar(514) "Review_Text";
  dcl double "_Col1_" having label n' Score for "+jean, +pant, comfortable, +look, +pair"';
  dcl double "_Col2_" having label n' Score for "+small, +size, +run, +order, +large"';
  dcl double "_Col3_" having label n' Score for "+dress, +wear, +compliment, +dress, comfortable"';
  dcl double "_Col4_" having label n' Score for "+look, not, +dress, +make, +fabric"';
  dcl double "_Col5_" having label n' Score for "very, flattering, comfortable, +fit, +soft"';
  dcl double "_Col6_" having label n' Score for "+top, +wear, +compliment, great, +jean"';
  dcl double "_Col7_" having label n' Score for "+color, +buy, beautiful, +soft, +fabric"';
  dcl double "_Col8_" having label n' Score for "not, +try, +store, +buy, +go"';
  dcl double "_Col9_" having label n' Score for "+shirt, +wear, +fit, +great, +love"';
  dcl double "_Col10_" having label n' Score for "+sweater, +wear, +sleeve, not, +soft"';
  dcl double "_Col11_" having label n' Score for "+great, +fit, +quality, perfect, great fit"';
  dcl double "_Col12_" having label n' Score for "+size, true, +fit, perfectly, beautiful"';
  dcl double "_Col13_" having label n' Score for "+fit, too, petite, +length, +order"';
  dcl double "_Col14_" having label n' Score for "+cute, comfortable, +little, really, +run"';
  dcl double "_Col15_" having label n' Score for "+love, +fit, +dress, too, +color"';
  dcl double "_Col16_" having label n' Score for "+look, great, +love, +jean, +fit"';
  dcl double "_TextTopic_1" having label n'+jean, +pant, comfortable, +look, +pair';
  dcl double "_TextTopic_2" having label n'+small, +size, +run, +order, +large';
  dcl double "_TextTopic_3" having label n'+dress, +wear, +compliment, +dress, comfortable';
  dcl double "_TextTopic_4" having label n'+look, not, +dress, +make, +fabric';
  dcl double "_TextTopic_5" having label n'very, flattering, comfortable, +fit, +soft';
  dcl double "_TextTopic_6" having label n'+top, +wear, +compliment, great, +jean';
  dcl double "_TextTopic_7" having label n'+color, +buy, beautiful, +soft, +fabric';
  dcl double "_TextTopic_8" having label n'not, +try, +store, +buy, +go';
  dcl double "_TextTopic_9" having label n'+shirt, +wear, +fit, +great, +love';
  dcl double "_TextTopic_10" having label n'+sweater, +wear, +sleeve, not, +soft';
  dcl double "_TextTopic_11" having label n'+great, +fit, +quality, perfect, great fit';
  dcl double "_TextTopic_12" having label n'+size, true, +fit, perfectly, beautiful';
  dcl double "_TextTopic_13" having label n'+fit, too, petite, +length, +order';
  dcl double "_TextTopic_14" having label n'+cute, comfortable, +little, really, +run';
  dcl double "_TextTopic_15" having label n'+love, +fit, +dress, too, +color';
  dcl double "_TextTopic_16" having label n'+look, great, +love, +jean, +fit';
  varlist allvars[_all_];
  method init();
    sc.setvars(allvars);
    sc.setKey(n'9314936A619A629E6C19A2802A0CEEC3274F9289');
  end;
  method preScoreRecord();
  end;
  method postScoreRecord();
  end;
  method term();
  end;
  method run();
    set sasep.in;
    preScoreRecord();
    sc.scoreRecord();
    postScoreRecord();
  end;
enddata;
