/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2024.10                                                     */
/* Component Version:  V2024.09                                                     */
/* CAS Version:        V.04.00M0P10142024                                           */
/* SAS Version:        V.04.00M0P101424                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       09baaac8-afa5-41ea-abe1-0f72329034f7                         */
/* Node GUID:          4df70b5c-5c20-4347-bfad-81080bd229ca                         */
/* Node Id:            4M5YXB4TXGV4V0OYH4GR4ZLXM                                    */
/* Algorithm:          Forest                                                       */
/* Generated by:       geladm                                                       */
/* Date:               04DEC2024:16:32:55                                           */
/*----------------------------------------------------------------------------------*/
data sasep.out;
   dcl package score _4M5YXB4TXGV4V0OYH4GR4ZLXM();
   dcl double EM_EVENTPROBABILITY;
   dcl double "Age";
   dcl nchar(12) EM_CLASSIFICATION;
   dcl double EM_PROBABILITY;
   dcl double "HoursPerWeek";
   dcl varchar(6) "Sex";
   dcl varchar(12) "Education";
   dcl varchar(21) "MartialStatus";
   dcl varchar(17) "Occupation";
   dcl varchar(18) "Race";
   dcl varchar(14) "Relationship";
   dcl varchar(16) "WorkClass";
   dcl double "P_GE50K1" having label n'Predicted: GE50K=1';
   dcl double "P_GE50K0" having label n'Predicted: GE50K=0';
   dcl nchar(12) "I_GE50K" having label n'Into: GE50K';
   dcl nchar(4) "_WARN_" having label n'Warnings';
   varlist allvars [_all_];
 
    
   method init();
      _4M5YXB4TXGV4V0OYH4GR4ZLXM.setvars(allvars);
      _4M5YXB4TXGV4V0OYH4GR4ZLXM.setkey(n'FD216DE7A5F0C438A35734FED721A596A4CE985F');
   end;
    
   method post_4M5YXB4TXGV4V0OYH4GR4ZLXM();
      dcl double _P_;
       
      if "P_GE50K0" = . then "P_GE50K0" = 0.7591904426;
      if "P_GE50K1" = . then "P_GE50K1" = 0.2408095574;
      if MISSING("I_GE50K") then do ;
      _P_ = 0.0;
      if "P_GE50K1" > _P_ then do ;
      _P_ = "P_GE50K1";
      "I_GE50K" = '           1';
      end;
      if "P_GE50K0" > _P_ then do ;
      _P_ = "P_GE50K0";
      "I_GE50K" = '           0';
      end;
      end;
      EM_EVENTPROBABILITY = "P_GE50K1";
      EM_CLASSIFICATION = "I_GE50K";
      EM_PROBABILITY = MAX("P_GE50K0", "P_GE50K1");
    
   end;
    
 
   method run();
      set SASEP.IN;
      _4M5YXB4TXGV4V0OYH4GR4ZLXM.scoreRecord();
      post_4M5YXB4TXGV4V0OYH4GR4ZLXM();
   end;
 
   method term();
   end;
 
enddata;
